version: '3'

services:
  dev:
    build:
      context: ./
      dockerfile: .docker/node/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
      - bi

  db:
    image: postgres:12
    restart: unless-stopped 
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432

  bi:
    image: mongo
    restart: unless-stopped 
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
      # MONGO_INITDB_DATABASE: code-challenge
    volumes:
      - ./dbdata/mongo:/data
    ports:
      - 27017:27017